### ISSUE TITLE
How to train the image variation model  

### ISSUE THREAD

**Issue by houxianxu** [justinpinkney/stable-diffusion#18]
Hi Justin,

Thank you for sharing the great model and code.

Could you please give me some instructions on how to fine-tune the stable diffusion for image variation? 

All the best

**Comment by justinpinkney** [comment]
The original config is here: https://github.com/justinpinkney/stable-diffusion/blob/main/configs/stable-diffusion/sd-image-condition-finetune.yaml

I'll add more details in future

**Comment by wtliao** [comment]
@justinpinkney 
thanks for sharing the great work!
I am trying to train the image variation model. Could you share the script for tine-tuning the stable diffusion model for this task? Thanks
