### ISSUE TITLE
Datasets used in fine-tuning for inpainting

### ISSUE THREAD

**Issue by Yang-Shiyuan** [justinpinkney/stable-diffusion#21]
Huge thanks for your code contrubution first!
Looks like the inpainting model is fine-tuned on Liaon dataset, the provided script laion.py seems doesn't work, could you please provide the exact link so that i can access the dataset (or its subset)? Also, if the pretrained model weights are available, could you please share it? Thanks in advance  : )

**Comment by justinpinkney** [comment]
I haven't tried training an inpainting model. I think that code was leftover from the original repo (pesser/stable-diffusion)
