### ISSUE TITLE
cfg for image variations

### ISSUE THREAD

**Issue by nikitabalabin** [justinpinkney/stable-diffusion#28]
Hello
Why do you use uc (unconditional tokens) as zeros for image variations?
Did you zero condition with p=0.1 in training process?

**Comment by justinpinkney** [comment]
yes I zero out with a 10% probability. I use zeros as this seems like a decent null condition, e.g. you can't use an empty string like for the text encoder. I guess you could have done a grey image instead, but not sure if it would make any difference.
