### ISSUE TITLE
Some confusion about the ckpt size

### ISSUE THREAD

**Issue by ssxxx1a** [justinpinkney/stable-diffusion#29]
thanks for your work!
there are some confusion for the saved ckpt.
I used the example for finetune, but I noticed that the ckpt file size is 13.6G, but the official pretrained models from stable model are 7.2G. What is the problem?
My first thought was that it was pytorch AMP, but I had an error after setting up pytorch_lightning, so I wanted to ask first~ 
@justinpinkney

**Comment by xiankgx** [comment]
Probably because the checkpoint is saving the CLIP model weights which contains two models in it with it.

**Comment by eeyrw** [comment]
It's about EMA parameter. The ckpt saves both model parameter and EMA parameter. The official pretrained weights removed the model parameter and kept EMA only.

**Comment by Line290** [comment]
It is optimizer state, delete it you can get a 7.2GB ckpt file.

**Comment by 065294847** [comment]
> It is optimizer state, delete it you can get a 7.2GB ckpt file.

How can I delete it? :)

**Comment by justinpinkney** [comment]
use this script: https://github.com/justinpinkney/stable-diffusion/blob/main/scripts/prune-ckpt.py
