### ISSUE TITLE
Demo was updated but example files not included in repository

### ISSUE THREAD

**Issue by HPlumley** [justinpinkney/stable-diffusion#4]
Commit https://github.com/justinpinkney/stable-diffusion/commit/db17cd8f41c2773d0fb97495470d545e44da07b7 added demos but the required assets were not included in the commit so running gradio_variations.py will currently result in an error.

Can be worked around by creating files assets/im-examples/vermeer.jpg and assets/im-examples/matisse.jpg

**Comment by justinpinkney** [comment]
I've added these now, thanks for pointing out!
