### ISSUE TITLE
Support for version 2?

### ISSUE THREAD

**Issue by ruoshiliu** [justinpinkney/stable-diffusion#57]
Hi @justinpinkney, thank you for sharing the repo! The results are amazing! I noticed the version 2 of the model has been released on huggingface but I haven't find a way to properly load the weights downloaded from huggingface to this repo. I can keep investigating but was just wondering if you could kindly provide the inference config file and perhaps share the model weights in stable-diffusion format (.ckpt)? That'll be immensely helpful. Thank you in advance!

**Comment by justinpinkney** [comment]
no support for v2 planned, sorry
