### ISSUE TITLE
Half Precision

### ISSUE THREAD

**Issue by TheLastBen** [justinpinkney/stable-diffusion#8]
If there is a way to convert it to half precision, because it is impossible to run it with 8GB of VRAM

**Comment by justinpinkney** [comment]
It should be possible to run in fp16, follow the same method for running a normal stable diffusion checkpoint in fp16 should work the same.

If there are memory issues you might also like to look at the version ported to huggingface Diffusers which has some features to help with memory consumption: https://github.com/LambdaLabsML/lambda-diffusers

**Comment by TheLastBen** [comment]
Thanks for the answer, but I'm getting **"addmm_impl_cpu_" not implemented for 'Half'** when I try to run it in fp16 mode

**Comment by justinpinkney** [comment]
hmmm, looks like it's on cpu from the error above?
